stages:
  - test

test:
  image: node:22
  stage: test
  script:
    - apt-get update && apt-get install libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - yarn install
    - yarn start &
    - yarn cypress:run